### ISSUE TITLE
Unknown timezone

### ISSUE THREAD

**Issue by sTiKyt** [OlivierMary/aw-watcher-jetbrains#103]
![image](https://user-images.githubusercontent.com/35602029/216152143-642898ed-a4e8-45e8-acf2-2835c74cac21.png)

**Comment by sTiKyt** [comment]
> Just submit v2.0.0 to JB review when publish can you tell me if changes works for you?

Sure

**Comment by sTiKyt** [comment]
Error message is gone now

**Comment by OlivierMary** [comment]
Good new ! have some issue on windows if needed #113

**Comment by sTiKyt** [comment]
Linux user here 😅
