### ISSUE TITLE
Can't find server

### ISSUE THREAD

**Issue by skeemer** [OlivierMary/aw-watcher-jetbrains#113]
As soon as I open PhpStorm, there's a notification:
"Activity Watcher Server connexion lost? Will try to re-send events when connexion back."

I updated to the 2.0.2 plugin version and then I started having issues where the IDE was freezing related to something in aw-watcher. I've always had a bit of connection issues so I reinstalled AW. I completely deleted the data directory before bringing it back up. I switched it to the rust server and everything seems to be up and running smooth except this watcher. The chrome extension connects without issues. I've restarted a couple times in case it was somehow networking related.

Is there something I can do to help debug this?

Windows 11
ActivityWatch 0.12.1
PhpStorm 2022.3.2

**Comment by OlivierMary** [comment]
It's very slow for me too on window versus linux.... have to check if any issue in aw-server.

I think it's a windows issue, cause I got same error on Idea, Goland and PhpStrom on windows an no issue on Linux

Will try to fix asap

**Comment by OlivierMary** [comment]
Ok I have a solution, it's the very slow aw-server on windows cause many timeout cause aw-server reply many times > 10s.
That will be fixed in v2.0.4.

And for aw-server-rust it slow for me ! And another swagger schema, I fix schema to match both server in v2.0.4 too.

**Comment by OlivierMary** [comment]
https://github.com/OlivierMary/aw-watcher-jetbrains/releases/tag/v2.0.4 if want to test before JB validation

**Comment by skeemer** [comment]
I installed that release manually and it appears to be working quite well.
It still comes up with the connection lost message first but then connects after 10-15s and haven't had any other issues. That happens on every start.
Thank you for the quick fix!

**Comment by OlivierMary** [comment]
@skeemer yes I see that, I have to check if it's for the first creation of bucket or just first test, or just the first heart beat process before the first reply of bucket... v2.0.4 just pass validation process.

**Comment by OlivierMary** [comment]
ok I found pb, fix in 2.0.5
