### ISSUE TITLE
Miscategorizing C as ObjectiveC

### ISSUE THREAD

**Issue by L1Z3** [OlivierMary/aw-watcher-jetbrains#122]
I installed the plugin on CLion (plugin version 2.0.8 from JetBrains Marketplace). Whenever I have a C file open, (`.c` or `.h`), the plugins reports my time as being spent in ObjectiveC instead of C.

Simple C hello world program in CLion:
![image](https://user-images.githubusercontent.com/10276179/227748474-86868847-da6e-4b9b-853a-59b8467e48e2.png)

Yet, ActivityWatch shows ObjectiveC:
![image](https://user-images.githubusercontent.com/10276179/227748502-b564c68c-3f91-41ae-964e-846386d159fe.png)

**Comment by OlivierMary** [comment]
Hi,

Jetsbrain API give me this information I didn't compute it.

```java
                    .file(file.getPresentableName()).fileFullPath(file.getPath()).project(project.getName()).language(file.getFileType().getName());
```

Objective-C is extension of C.
Have to check if I can influence this with project type or something else.

**Comment by OlivierMary** [comment]
It's CLion which return Objective-C. With IDEA I got C++ and Objective-C on CLion for the same file.

**Comment by OlivierMary** [comment]
@L1Z3 I just sent a new version to Jetbrains plugin verification process. That will be better results in `v2.0.9`

tell me if not ;)

**Comment by L1Z3** [comment]
Just tried `v2.0.9` from the GitHub releases. It seems to work now! It correctly reports `C/C++`.

**Comment by OlivierMary** [comment]
Good :) I close :) !
