### ISSUE TITLE
Allow to track current branch and commit 

### ISSUE THREAD

**Issue by kimond** [OlivierMary/aw-watcher-jetbrains#3]
[Wakatime](https://wakatime.com) keeps track of the current branch and time spend on a commit.
I think adding a new tag with the current branch would be simple.
However, the time spends on a commit seems to be a more complicated issue.

**Comment by OlivierMary** [comment]
Just submit v2.0.0 to JB review when publish can you tell me if changes works for you?

I added, commit sha1, branch and repo url
