### ISSUE TITLE
Considering not taking background time into account?

### ISSUE THREAD

**Issue by onlyice** [OlivierMary/aw-watcher-jetbrains#30]
This plugin is really convenient and helpful. But there's a situation that can be handled better.

I open PyCharm to work on my project. Then I switch to Google Chrome to view some documents. But the time I'm not editing the code file in PyCharm is collected and reported to the Activity Watch server. This is mostly not as expected.

**Comment by OlivierMary** [comment]
Hi,

On Jetbrains IDEs I can only get IDEs events, and there is no event like "Left IDE", "Back to IDE".

For that it's on activity watch to do something.... You can get time pass on each app, and afk times.

Or if no interaction since 60sec I dont record ? Not really good You can pass 5min to watch a code part no, how to set a good limit... ?

**Comment by onlyice** [comment]
> Or if no interaction since 60sec I dont record ? Not really good You can pass 5min to watch a code part no, how to set a good limit... ?

I think it's a good idea. Maybe you can provide an option for user to specify the heartbeat suspending timeout?

**Comment by OlivierMary** [comment]
Why not, by default no timeout and if need a configurable timeout.

**Comment by johan-bjareholt** [comment]
>  Or if no interaction since 60sec I dont record ? Not really good You can pass 5min to watch a code part no, how to set a good limit... ?

This is how many other editor watchers do it. At least that's how I did it in aw-watcher-vim but if I remember correctly I've seen other editor watchers doing it this way too.

**Comment by OlivierMary** [comment]
Just submit v2.0.0 to JB review when publish can you tell me if changes works for you?

**Comment by OlivierMary** [comment]
@tmotyl I see some issues on windows and rust server see #113 , have to wait validation of 2.0.4.

**Comment by tmotyl** [comment]
Thanks @OlivierMary for taking care. Highly appreciated!
