### ISSUE TITLE
Enormous amount of logged time

### ISSUE THREAD

**Issue by asm0dey** [OlivierMary/aw-watcher-jetbrains#61]
It's only 9:52AM MSK, but amount of logged time is already more than 14 hours:

![image](https://user-images.githubusercontent.com/1297282/84473930-90a29c00-ac92-11ea-93b3-7f4c115607c1.png)

**Comment by OlivierMary** [comment]
Hi there,


You stay all night on "linuxSecretLibrary.kt" ? This time is normally evicted by afktime form windows agent.

**Comment by asm0dey** [comment]
Hah, not sure, but as of me it should have been cut at 00:00

**Comment by Tagman** [comment]
I also have that problem. Opened the project windows around 30mins ago. Tracker already says smth like 2+hrs.
Is it maybe accumulating all the opened tabs?

![image](https://user-images.githubusercontent.com/1387323/105161393-a1ad6880-5b11-11eb-919d-f5da8a41082b.png)

**Comment by fbjorn** [comment]
Hi there from 2023, the problem still exists. When I go to sleep (physically) and open my IDE the next day, the last opened project is tracked as being active for the time I was inactive. So AFK status is not taken into account. Do you have any ideas how this could be resolved on a plugin level? Or the only option is to filter data somehow from the ActivityWatch dasboard?

**Comment by OlivierMary** [comment]
Hi there, sorry for that, actually I have no time to work on it, I think that need a good refactoring...

**Comment by OlivierMary** [comment]
Just submit v2.0.0 to JB review when publish can you tell me if changes works for you?
